apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  namespace: default
  labels:
    app: ml-api
spec:
  replicas: 2
  minReadySeconds: 5
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      name: ml-pod
      labels:
        app: ml-api
    spec:
      containers:
      - name: ml-container
        image: gcr.io/PROJECT_ID/appcicd:COMMIT_SHA
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        lifecycle:
          preStop:
            exec:
              command: 
                - "sh"
                - "-c"
                - "sleep 5"
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          httpGet:
            path: /
            port: 8080